// hive-ai-frontend/src/components/MarkdownContent.vue
<template>
  <div v-if="html" class="markdown-body" v-html="html" />
  <div v-else-if="content" class="markdown-body plain-fallback">{{ content }}</div>
</template>

<script setup>
import { computed } from 'vue'
import { renderMarkdown } from '../utils/markdown'

const props = defineProps({
  content: { type: String, default: '' },
})

const html = computed(() => renderMarkdown(props.content))
</script>

<style src="../styles/markdown.css"></style>

<style scoped>
.plain-fallback {
  white-space: pre-wrap;
}
</style>

// hive-ai-frontend-React/src/components/MarkdownContent.tsx
import { useMemo } from 'react'
import { renderMarkdown } from '@/utils/markdown'
import '@/styles/markdown.css'

interface MarkdownContentProps {
  content: string
  className?: string
}

export function MarkdownContent({ content, className = '' }: MarkdownContentProps) {
  const html = useMemo(() => renderMarkdown(content), [content])

  if (html) {
    return (
      <div
        className={`markdown-body ${className}`.trim()}
        dangerouslySetInnerHTML={{ __html: html }}
      />
    )
  }

  if (content) {
    return <div className={`markdown-body plain-fallback ${className}`.trim()}>{content}</div>
  }

  return null
}
